generate_custom_theme_title_slide_overrides <- function() {
  c(
    "/* TITLE SLIDE SECTION LINK OVERRIDES - Must be last to ensure precedence */",
    ".reveal .slides section.title a,",
    ".reveal .slides section.title * a,",
    ".reveal .slides section.title a:link,",
    ".reveal .slides section.title a:visited,",
    ".reveal .slides section.title a:active,",
    ".reveal .slides section.title .r-fit-text a,",
    ".reveal .slides section.title .columns a,",
    ".reveal .slides section.title .column a,",
    ".reveal .title a,",
    ".reveal .title * a,",
    ".reveal .title .r-fit-text a,",
    ".reveal .title .columns a,",
    ".reveal .title .column a {",
    "  color: $backgroundColor !important;",
    "  text-decoration: underline !important;",
    "  text-decoration-color: $backgroundColor !important;",
    "  background-color: transparent !important;",
    "",
    "  &:hover,",
    "  &:focus,",
    "  &:active {",
    "    color: $headingColor !important;",
    "    background-color: $backgroundColor !important;",
    "    border-radius: 3px !important;",
    "    padding: 2px 4px !important;",
    "    text-decoration: underline !important;",
    "    text-decoration-color: $headingColor !important;",
    "  }",
    "}"
  )
}
