generate_html_heading_styles <- function() {
  c(
    "// Heading styles with brand colors",
    "h1, .h1 {",
    "  color: $headingColor;",
    "  font-family: $headings-font-family;",
    "  font-weight: $headings-font-weight;",
    "  line-height: $headings-line-height;",
    "  margin-bottom: $headings-margin-bottom;",
    "}",
    "",
    "h2, .h2 {",
    "  color: $headingColor;",
    "  font-family: $headings-font-family;",
    "  font-weight: $headings-font-weight;",
    "  line-height: $headings-line-height;",
    "  margin-bottom: $headings-margin-bottom;",
    "}",
    "",
    "h3, .h3 {",
    "  color: $headingColor;",
    "  font-family: $headings-font-family;",
    "  font-weight: $headings-font-weight;",
    "  line-height: $headings-line-height;",
    "  margin-bottom: $headings-margin-bottom;",
    "}",
    "",
    "h4, .h4, h5, .h5, h6, .h6 {",
    "  color: $bodyColor;",
    "  font-family: $headings-font-family;",
    "  font-weight: $headings-font-weight;",
    "  line-height: $headings-line-height;",
    "  margin-bottom: $headings-margin-bottom;",
    "}"
  )
}
