generate_custom_theme_link_styles <- function() {
  c(
    "pre a,",
    ".reveal pre a,",
    "code a,",
    ".reveal code a {",
    "  color: $bodyColor;",
    "  text-decoration: underline;",
    "",
    "  &:hover {",
    "    color: $linkColor;",
    "    background-color: $bodyColor;",
    "  }",
    "}",
    "",
    "a,",
    ".reveal a,",
    ".reveal .footer a {",
    "  color: $linkColor !important;",
    "  text-decoration: underline !important;",
    "",
    "  &:hover {",
    "    color: $bodyColor !important;",
    "    background-color: $linkColor !important;",
    "  }",
    "}",
    "",
    "/* Specific styling for links in title slides and slides with background colors */",
    ".reveal .slides section a,",
    ".reveal .title-slide a,",
    ".reveal .bg-dark_green a,",
    ".reveal .slide-background a {",
    "  color: $linkColor !important;",
    "  text-decoration: underline !important;",
    "",
    "  &:hover {",
    "    color: $backgroundColor !important;",
    "    background-color: $linkColor !important;",
    "  }",
    "}",
    "",
    "/* Force color for all links, overriding any reveal.js defaults */",
    ".reveal a:link,",
    ".reveal a:visited,",
    ".reveal a:active {",
    "  color: $linkColor !important;",
    "}"
  )
}
