generate_custom_theme_utility_classes <- function(custom_theme) {
  c(
    "/* Utility text classes */",
    ".text-bold {",
    "  font-weight: bold;",
    "}",
    "",
    ".text-italic {",
    "  font-style: italic;",
    "}",
    "",
    ".text-underline {",
    "  text-decoration: underline;",
    "}",
    "",
    ".text-strike {",
    "  text-decoration: line-through;",
    "}",
    "",
    ".text-uppercase {",
    "  text-transform: uppercase;",
    "}",
    "",
    ".text-lowercase {",
    "  text-transform: lowercase;",
    "}",
    "",
    ".text-capitalize {",
    "  text-transform: capitalize;",
    "}",
    "",
    ".text-normal {",
    "  text-transform: none;",
    "}",
    "",
    ".text-center {",
    "  text-align: center;",
    "}",
    "",
    ".text-left {",
    "  text-align: left;",
    "}",
    "",
    ".text-right {",
    "  text-align: right;",
    "}",
    "",
    ".text-smaller {",
    "  font-size: $mainFontSize * 0.7 !important;",
    "}",
    "",
    ".text-tiny {",
    "  font-size: $mainFontSize * 0.3 !important;",
    "}",
    "",
    ".text-larger {",
    "  font-size: $mainFontSize * 1.3 !important;",
    "}",
    "",
    ".text-size-heading1 {",
    "  font-size: $heading1Size !important;",
    "}",
    "",
    ".text-size-heading2 {",
    "  font-size: $heading2Size !important;",
    "}",
    "",
    ".text-size-heading3 {",
    "  font-size: $heading3Size !important;",
    "}",
    "",
    ".text-size-heading4 {",
    "  font-size: $heading4Size !important;",
    "}",
    "",
    ".text-size-body {",
    "  font-size: $mainFontSize !important;",
    "}",
    "",
    ".text-shadow-light {",
    paste0("  text-shadow: ", custom_theme$shadows$lightTextShadow, " !important;"),
    "}",
    "",
    ".text-shadow-dark {",
    paste0("  text-shadow: ", custom_theme$shadows$darkTextShadow, " !important;"),
    "}",
    "",
    ".text-margin-bottom-15 {",
    "  margin-bottom: 15px !important;",
    "}",
    "",
    ".text-margin-top-15 {",
    "  margin-top: 15px;",
    "}"
  )
}
