generate_r_theme <- function(
  colors_file = here::here("Presentation/colors.json"),
  fonts_file = here::here("Presentation/fonts.json"),
  output_file = here::here("R/set_r_theme.R")
) {
  message("Generating set_r_theme.R...\n")

  # Check if input files exist
  if (
    !file.exists(colors_file)
  ) {
    stop("colors.json not found. Please create this file first.")
  }

  if (
    !file.exists(fonts_file)
  ) {
    stop("fonts.json not found. Please create this file first.")
  }

  # Read colors and fonts from JSON
  colors_data <- jsonlite::fromJSON(colors_file)
  fonts <- jsonlite::fromJSON(fonts_file)

  # Handle both old format (flat) and new format (nested)
  if (
    "primary" %in% names(colors_data)
  ) {
    # New nested format
    colors <- colors_data$primary
    semantic_colors <- if ("semantic" %in% names(colors_data)) colors_data$semantic else list()
  } else {
    # Old flat format (backward compatibility)
    colors <- colors_data
    semantic_colors <- list()
  }

  # Helper function to resolve semantic color references
  resolve_semantic_color <- function(semantic_name, default_value = NULL) {
    if (semantic_name %in% names(semantic_colors)) {
      color_ref <- semantic_colors[[semantic_name]]
      # If it references a primary color, return the hex value
      if (color_ref %in% names(colors)) {
        return(colors[[color_ref]])
      } else {
        return(color_ref)
      }
    } else if (!is.null(default_value)) {
      return(default_value)
    } else {
      return(NULL)
    }
  }

  # Generate R theme content
  r_theme_content <-
    c(
      "# This file is auto-generated from colors.json and fonts.json. Do not edit directly.",
      "# Generated by generate_theme.R",
      "",
      "#----------------------------------------------------------#",
      "# Brand Compliant R Theme Settings",
      "#----------------------------------------------------------#",
      "",
      "# Load required packages for theme",
      'if (!require("ggplot2")) stop("ggplot2 package is required")',
      'if (!require("sysfonts")) stop("sysfonts package is required for custom fonts")',
      'if (!require("showtext")) stop("showtext package is required for custom fonts")',
      "",
      "# Load Google Fonts using sysfonts with error handling",
      paste0("# Try to load ", fonts$body, " (may be named differently in Google Fonts)"),
      "tryCatch({",
      paste0('  sysfonts::font_add_google("', fonts$body, '", "', fonts$system$internalBodyName, '")'),
      "}, error = function(e) {",
      "  # Try alternative names for Plus Jakarta Sans",
      "  tryCatch({",
      paste0('    sysfonts::font_add_google("', fonts$system$bodyFallbacks[1], '", "', fonts$system$internalBodyName, '")'),
      "  }, error = function(e2) {",
      "    # Fallback to a similar font",
      paste0('    message("', fonts$body, " not found, using ", fonts$system$bodyFallbacks[2], ' as fallback")'),
      paste0('    sysfonts::font_add_google("', fonts$system$bodyFallbacks[2], '", "', fonts$system$internalBodyName, '")'),
      "  })",
      "})",
      "",
      paste0("# Load ", fonts$heading),
      "tryCatch({",
      paste0('  sysfonts::font_add_google("', fonts$heading, '", "', fonts$system$internalHeadingName, '")'),
      "}, error = function(e) {",
      paste0('  message("', fonts$heading, ' not found, using Roboto Condensed as fallback")'),
      paste0('  sysfonts::font_add_google("', fonts$system$headingFallbacks[1], '", "', fonts$system$internalHeadingName, '")'),
      "})",
      "",
      paste0("# Load ", fonts$monospace),
      "tryCatch({",
      paste0('  sysfonts::font_add_google("', fonts$monospace, '", "', fonts$system$internalMonoName, '")'),
      "}, error = function(e) {",
      paste0('  message("', fonts$monospace, " not found, using ", fonts$system$monospaceFallback, ' as fallback")'),
      paste0('  sysfonts::font_add_google("', fonts$system$monospaceFallback, '", "', fonts$system$internalMonoName, '")'),
      "})",
      "",
      "# Enable showtext for rendering custom fonts",
      "showtext::showtext_auto()",
      "",
      "# Brand Colors (from brand guidelines)",
      "colours <- c(",
      # Dynamically generate color entries from the colors object
      {
        color_entries <- purrr::imap_chr(colors, ~ paste0("  ", .y, ' = "', .x, '"'))
        # Add comma to all entries except the last one
        color_entries[-length(color_entries)] <- paste0(color_entries[-length(color_entries)], ",")
        color_entries
      },
      ")",
      "",
      "# Color Scales for ggplot2",
      "scale_colour_presentation <- function(...) ggplot2::scale_colour_manual(values = colours, ...)",
      "scale_fill_presentation <- function(...) ggplot2::scale_fill_manual(values = colours, ...)",
      "",
      "# Primary color sequence (for ordered data)",
      # Dynamically create primary sequence from first few non-white/black colors
      {
        non_neutral_colors <- colors[!names(colors) %in% c("white", "black", "gray")]
        if (length(non_neutral_colors) >= 3) {
          primary_seq <- paste0('"', non_neutral_colors[1:3], '"', collapse = ", ")
        } else {
          primary_seq <- paste0('"', non_neutral_colors, '"', collapse = ", ")
        }
        paste0("colors_primary_sequence <- c(", primary_seq, ")")
      },
      "",
      "# Diverging color palette (for diverging data)",
      # Create diverging palette using first color, white, and last color
      {
        if (length(non_neutral_colors) >= 2) {
          first_color <- non_neutral_colors[1]
          last_color <- non_neutral_colors[length(non_neutral_colors)]
          white_color <- if ("white" %in% names(colors)) colors$white else "#FFFFFF"
          paste0('colors_diverging <- c("', first_color, '", "', white_color, '", "', last_color, '")')
        } else {
          paste0('colors_diverging <- c("', non_neutral_colors[1], '", "', colors$white, '", "', non_neutral_colors[1], '")')
        }
      },
      "",
      "# Text and background colors",
      {
        text_color <- resolve_semantic_color("textColor", if ("black" %in% names(colors)) colors$black else "#000000")
        paste0('presentation_text_color <- "', text_color, '"')
      },
      {
        bg_color <- resolve_semantic_color("backgroundColor", if ("white" %in% names(colors)) colors$white else "#FFFFFF")
        paste0('presentation_background_color <- "', bg_color, '"')
      },
      {
        accent_color <- resolve_semantic_color("accentColor", non_neutral_colors[length(non_neutral_colors)])
        paste0('presentation_accent_color <- "', accent_color, '"')
      },
      "",
      "# Define typography (based on presentation brand guidelines)",
      "# Using registered font names from sysfonts",
      paste0('presentation_base_font <- "', fonts$system$internalBodyName, '"'),
      paste0('presentation_heading_font <- "', fonts$system$internalHeadingName, '"'),
      paste0('presentation_mono_font <- "', fonts$system$internalMonoName, '"'),
      "",
      "# Define text sizes (following brand hierarchy from fonts.json)",
      "# Convert px to pt: 1px ≈ 0.75pt (at 96 DPI)",
      paste0("text_size_main_px <- ", gsub("px", "", fonts$sizes$mainFontSize)),
      "text_size_main_pt <- text_size_main_px * 0.75  # Convert px to pt",
      "text_size_small <- text_size_main_pt * 0.8",
      "text_size_base <- text_size_main_pt * 0.9",
      "text_size_medium <- text_size_main_pt * 1.0",
      "text_size_large <- text_size_main_pt * 1.2",
      "text_size_xlarge <- text_size_main_pt * 1.4",
      "",
      "# Define line sizes",
      "line_size_thin <- 0.25",
      "line_size_base <- 0.5",
      "line_size_thick <- 1.0",
      "",
      "# Define output dimensions (standard sizes)",
      "image_width <- 16",
      "image_height <- 12",
      paste0('image_units <- "', fonts$system$imageUnits, '"'),
      "image_dpi <- 300",
      "",
      "# Create presentation-compliant ggplot2 theme",
      "theme_presentation <- function(base_size = text_size_base,",
      "                       base_family = presentation_base_font,",
      "                       base_line_size = line_size_base,",
      "                       base_rect_size = line_size_base) {",
      "  ggplot2::theme_bw(base_size = base_size,",
      "                   base_family = base_family,",
      "                   base_line_size = base_line_size,",
      "                   base_rect_size = base_rect_size) +",
      "  ggplot2::theme(",
      "    # Text elements",
      {
        text_color <- resolve_semantic_color("textColor", if ("black" %in% names(colors)) colors$black else "#000000")
        paste0('    text = ggplot2::element_text(family = presentation_base_font, colour = "', text_color, '"),')
      },
      {
        # Get heading color from semantic colors or fallback to first non-neutral color
        heading_color <- resolve_semantic_color(
          "headingColor",
          if (length(non_neutral_colors) > 0) non_neutral_colors[1] else (if ("black" %in% names(colors)) colors$black else "#000000")
        )
        paste0('    plot.title = ggplot2::element_text(family = presentation_heading_font, colour = "', heading_color, '", face = "', fonts$ggplot$plotTitleFace, '", size = ggplot2::rel(', fonts$ggplot$plotTitleSize, ")),")
      },
      {
        text_color <- resolve_semantic_color("textColor", if ("black" %in% names(colors)) colors$black else "#000000")
        paste0('    plot.subtitle = ggplot2::element_text(family = presentation_base_font, colour = "', text_color, '", size = ggplot2::rel(', fonts$ggplot$plotSubtitleSize, ")),")
      },
      {
        text_color <- resolve_semantic_color("textColor", if ("black" %in% names(colors)) colors$black else "#000000")
        paste0('    axis.title = ggplot2::element_text(family = presentation_base_font, colour = "', text_color, '", size = ggplot2::rel(', fonts$ggplot$axisTitleSize, ")),")
      },
      {
        text_color <- resolve_semantic_color("textColor", if ("black" %in% names(colors)) colors$black else "#000000")
        paste0('    axis.text = ggplot2::element_text(family = presentation_base_font, colour = "', text_color, '", size = ggplot2::rel(', fonts$ggplot$axisTextSize, ")),")
      },
      {
        text_color <- resolve_semantic_color("textColor", if ("black" %in% names(colors)) colors$black else "#000000")
        paste0('    legend.title = ggplot2::element_text(family = presentation_base_font, colour = "', text_color, '", size = ggplot2::rel(', fonts$ggplot$legendTitleSize, ")),")
      },
      {
        text_color <- resolve_semantic_color("textColor", if ("black" %in% names(colors)) colors$black else "#000000")
        paste0('    legend.text = ggplot2::element_text(family = presentation_base_font, colour = "', text_color, '", size = ggplot2::rel(', fonts$ggplot$legendTextSize, ")),")
      },
      {
        # Use heading color for strip text
        heading_color <- resolve_semantic_color(
          "headingColor",
          if (length(non_neutral_colors) > 0) non_neutral_colors[1] else (if ("black" %in% names(colors)) colors$black else "#000000")
        )
        paste0('    strip.text = ggplot2::element_text(family = presentation_heading_font, colour = "', heading_color, '", face = "', fonts$ggplot$stripTextFace, '"),')
      },
      "    ",
      "    # Background elements",
      {
        bg_color <- resolve_semantic_color("backgroundColor", if ("white" %in% names(colors)) colors$white else "#FFFFFF")
        paste0('    plot.background = ggplot2::element_rect(fill = "', bg_color, '", colour = NA),')
      },
      {
        bg_color <- resolve_semantic_color("backgroundColor", if ("white" %in% names(colors)) colors$white else "#FFFFFF")
        paste0('    panel.background = ggplot2::element_rect(fill = "', bg_color, '", colour = NA),')
      },
      "    legend.background = ggplot2::element_blank(),",
      "    legend.key = ggplot2::element_blank()",
      "  )",
      "}",
      "",
      "# Set the default ggplot2 theme to presentation theme",
      "ggplot2::theme_set(theme_presentation())",
      "",
      "# Helper functions for common presentation visualizations",
      "presentation_discrete_colors <- function(n) {",
      "  if (n <= length(colours)) {",
      "    return(colours[1:n])",
      "  } else {",
      "    # Generate more colors using colorRampPalette if needed",
      "    return(colorRampPalette(colours)(n))",
      "  }",
      "}",
      "",
      "# Export commonly used values for backward compatibility",
      "text_size <- text_size_base",
      "line_size <- line_size_base"
    )

  # Write to set_r_theme.R
  writeLines(
    text = r_theme_content,
    con = output_file
  )

  message("set_r_theme.R generated successfully\n")
}
