generate_custom_theme_heading_styles <- function(custom_theme) {
  c(
    "/* Headings */",
    "h1,",
    "h2,",
    "h3,",
    "h4,",
    ".reveal h1,",
    ".reveal h2,",
    ".reveal h3,",
    ".reveal h4 {",
    "  font-family: $headingFont !important;",
    "  line-height: $headingLineHeight;",
    "  letter-spacing: $headingLetterSpacing;",
    "  text-transform: $headingTextTransform;",
    "  font-weight: $headingFontWeight;",
    "  margin: $headingMargin;",
    "  color: $headingColor;",
    "  text-shadow: $heading1TextShadow;",
    "}",
    "",
    "h1,",
    ".reveal h1 {",
    "  font-size: $heading1Size !important;",
    "  margin-top: $blockMargin;",
    "}",
    "",
    "h2,",
    ".reveal h2 {",
    "  font-size: $heading2Size !important;",
    "  margin-top: $blockMargin;",
    "}",
    "",
    "h3,",
    ".reveal h3 {",
    "  font-size: $heading3Size !important;",
    "  margin-top: $smallMargin;",
    "}",
    "",
    "h4,",
    ".reveal h4 {",
    "  font-size: $heading4Size !important;",
    "  margin-top: $smallMargin;",
    "}",
    "",
    "/* Additional Reveal.js specific heading font rules */",
    ".reveal .slides section .fragment h1,",
    ".reveal .slides section .fragment h2,",
    ".reveal .slides section .fragment h3,",
    ".reveal .slides section .fragment h4,",
    ".reveal .slides section h1,",
    ".reveal .slides section h2,",
    ".reveal .slides section h3,",
    ".reveal .slides section h4 {",
    "  font-family: $headingFont !important;",
    "}",
    "",
    "/* Ensure heading classes also use the correct font */",
    ".text-font-heading,",
    ".reveal .text-font-heading {",
    "  font-family: $headingFont !important;",
    "}"
  )
}
