# This file is auto-generated from colors.json and fonts.json. Do not edit directly.
# Generated by generate_theme.R

#----------------------------------------------------------#
# SPROuT Brand Compliant R Theme Settings
#----------------------------------------------------------#

# Load required packages for theme
if (!require("ggplot2")) stop("ggplot2 package is required")
if (!require("sysfonts")) stop("sysfonts package is required for custom fonts")
if (!require("showtext")) stop("showtext package is required for custom fonts")

# Load Google Fonts using sysfonts with error handling
# Try to load Inconsolata (may be named differently in Google Fonts)
tryCatch({
  sysfonts::font_add_google("Inconsolata", "internal_body")
}, error = function(e) {
  # Try alternative names for Plus Jakarta Sans
  tryCatch({
    sysfonts::font_add_google("Courier New", "internal_body")
  }, error = function(e2) {
    # Fallback to a similar font
    message("Inconsolata not found, using monospace as fallback")
    sysfonts::font_add_google("monospace", "internal_body")
  })
})

# Load Poppins
tryCatch({
  sysfonts::font_add_google("Poppins", "internal_heading")
}, error = function(e) {
  message("Poppins not found, using Roboto Condensed as fallback")
  sysfonts::font_add_google("Arial", "internal_heading")
})

# Load JetBrains Mono
tryCatch({
  sysfonts::font_add_google("JetBrains Mono", "internal_mono")
}, error = function(e) {
  message("JetBrains Mono not found, using Fira Code as fallback")
  sysfonts::font_add_google("Fira Code", "internal_mono")
})

# Enable showtext for rendering custom fonts
showtext::showtext_auto()

# SPROuT Brand Colors (from brand guidelines)
sprout_cols <- c(
  white = "#ffffff",
  black = "#000000",
  grey = "#cccccc",
  blue = "#415280",
  purple = "#8a5697",
  pink = "#d55288",
  coral = "#eb5f56",
  orange = "#ff9714",
  green = "#6c6934"
)

# SPROuT Color Scales for ggplot2
scale_colour_SPROuT <- function(...) ggplot2::scale_colour_manual(values = sprout_cols, ...)
scale_fill_SPROuT <- function(...) ggplot2::scale_fill_manual(values = sprout_cols, ...)

# Primary color sequence (for ordered data)
SPROuT_primary_sequence <- c("#cccccc", "#415280", "#8a5697")

# Diverging color palette (for diverging data)
SPROuT_diverging <- c("#cccccc", "#ffffff", "#6c6934")

# Text and background colors
SPROuT_text_color <- "#000000"
SPROuT_background_color <- "#ffffff"
SPROuT_accent_color <- "#8a5697"

# Define typography (based on SPROuT brand guidelines)
# Using registered font names from sysfonts
SPROuT_base_font <- "internal_body"
SPROuT_heading_font <- "internal_heading"
SPROuT_mono_font <- "internal_mono"

# Define text sizes (following brand hierarchy from fonts.json)
# Convert px to pt: 1px ˜ 0.75pt (at 96 DPI)
text_size_main_px <- 30
text_size_main_pt <- text_size_main_px * 0.75  # Convert px to pt
text_size_small <- text_size_main_pt * 0.8
text_size_base <- text_size_main_pt * 0.9
text_size_medium <- text_size_main_pt * 1.0
text_size_large <- text_size_main_pt * 1.2
text_size_xlarge <- text_size_main_pt * 1.4

# Define line sizes
line_size_thin <- 0.25
line_size_base <- 0.5
line_size_thick <- 1.0

# Define output dimensions (standard sizes)
image_width <- 16
image_height <- 12
image_units <- "cm"
image_dpi <- 300

# Create SPROuT-compliant ggplot2 theme
theme_SPROuT <- function(base_size = text_size_base,
                       base_family = SPROuT_base_font,
                       base_line_size = line_size_base,
                       base_rect_size = line_size_base) {
  ggplot2::theme_bw(base_size = base_size,
                   base_family = base_family,
                   base_line_size = base_line_size,
                   base_rect_size = base_rect_size) +
  ggplot2::theme(
    # Text elements
    text = ggplot2::element_text(family = SPROuT_base_font, colour = "#000000"),
    plot.title = ggplot2::element_text(family = SPROuT_heading_font, colour = "#000000", face = "bold", size = ggplot2::rel(1.4)),
    plot.subtitle = ggplot2::element_text(family = SPROuT_base_font, colour = "#000000", size = ggplot2::rel(1.1)),
    axis.title = ggplot2::element_text(family = SPROuT_base_font, colour = "#000000", size = ggplot2::rel(1)),
    axis.text = ggplot2::element_text(family = SPROuT_base_font, colour = "#000000", size = ggplot2::rel(0.9)),
    legend.title = ggplot2::element_text(family = SPROuT_base_font, colour = "#000000", size = ggplot2::rel(1)),
    legend.text = ggplot2::element_text(family = SPROuT_base_font, colour = "#000000", size = ggplot2::rel(0.9)),
    strip.text = ggplot2::element_text(family = SPROuT_heading_font, colour = "#000000", face = "bold"),
    
    # Background elements
    plot.background = ggplot2::element_rect(fill = "#ffffff", colour = NA),
    panel.background = ggplot2::element_rect(fill = "#ffffff", colour = NA),
    legend.background = ggplot2::element_blank(),
    legend.key = ggplot2::element_blank()
  )
}

# Set the default ggplot2 theme to SPROuT theme
ggplot2::theme_set(theme_SPROuT())

# Helper functions for common SPROuT visualizations
SPROuT_discrete_colors <- function(n) {
  if (n <= length(sprout_cols)) {
    return(sprout_cols[1:n])
  } else {
    # Generate more colors using colorRampPalette if needed
    return(colorRampPalette(sprout_cols)(n))
  }
}

# Export commonly used values for backward compatibility
text_size <- text_size_base
line_size <- line_size_base
